version: '1.0'
name: pipeline-20230508
displayName: pipeline-20230508
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: ut@maven
        name: unit_test_maven
        displayName: Maven 单元测试
        jdkVersion: '8'
        mavenVersion: 3.3.9
        commands:
          - '# Maven单元测试默认命令'
          - mvn -B test
          - mvn surefire-report:report-only
          - mvn site -DgenerateReports=false
        report:
          path: ./target/site
          index: surefire-report.html
        checkpoints: []
        settings: []
        caches:
          - ~/.m2
        notify: []
        strategy:
          retry: '0'
